Repository JNU-econovation/Let-s-git-it-started-2024, pull requests merged in 2024-12, with the labels that each got.

#66 [이준서] 2024-2학기 깃행사 실습
  .github/PULL_REQUEST_TEMPLATE.md
  introduction/LEEJUNSEO.md
  introduction/picture/leejs.jpg
Labels: 28기

#71 [강하은] 2024-2학기 깃행사 실습
  1st_Let_s_git_it_started(Git_tutorial)/introduction/kanghaeun.md
  1st_Let_s_git_it_started(Git_tutorial)/picture/photo.jpeg
Labels: 26기

#81 [정승현] 2024-2학기 깃행사 실습
  1st_Let_s_git_it_started(Git_tutorial)/introduction/JungSeungHyeon.md
  1st_Let_s_git_it_started(Git_tutorial)/picture/picture.jpeg
Labels: 27기

#83 정의찬 2024-2학기 깃행사 실습
  1st_Let_s_git_it_started(Git_tutorial)/introduction/euichan.md
  1st_Let_s_git_it_started(Git_tutorial)/picture/test.png
Labels: 28기

#120 feat: Happy 출력 구현
  Team-2/test.py
Labels: Team2

#123 feat: 곱하기를 출력한다
  Team-4/hello.py
Labels: Team4

#117 feat: New 출력 구현
  Team-2/test.py
Labels: Team2

#134 add print Year
  Team-1/test.py
  introduction/LEEJUNSEO.md
  introduction/picture/leejs.jpg
Labels: Team1

#136 2025 출력
  Team3/Team3.py
Labels: Team3

#118 feat : 2025 출력
  Team-2/test.py
Labels: Team2

#122 feat: year출력
  Team-5/hello.py
Labels: Team5

#124 feat: 나누기 출력
  Team-4/hello.py
Labels: Team4

#127 feat: 더하기를 출력한다
  Team-4/hello.py
Labels: Team4

#126 feat: 빼기를 출력한다
  Team-4/hello.py
Labels: Team4

#139 Feat/116/new
  Front/hello.js
Labels: Team6
