Repository JNU-econovation/Let-s-git-it-started-2024, pull requests merged in 2024-06, with the labels that each got.

#43 feat:add
  src/calc.py
Labels: Team3

#39 FEAT: 나누기 기능입니다
  src/.idea/.gitignore
  src/.idea/misc.xml
  src/.idea/modules.xml
  src/.idea/vcs.xml
  src/Let-s-git-it-started-2024.iml
  src/calc.java
Labels: Team5

#54 19/mainfunc
  src/calc.py
Labels: Team4

#42 feat: 뺄셈
  src/calc.js
Labels: Team2

#57 feat: mod 기능 추가
  src/calc.py
Labels: Team3

#60 feat: 나눗셈 기능 구현
  src/calc.py
Labels: Team4

#41 feat: 덧셈
  src/calc.js
Labels: Team2

#44 feat: 곱셈
  src/calc.js
Labels: Team2

#55 feat: multiply(#9)
  src/calc.py
Labels: Team3

#61 23/multiply
  src/calc.py
Labels: Team4

#58 20/sub
  src/calc.py
Labels: Team4

#59 21/add
  src/calc.py
Labels: Team4

#51 feat: sub 기능 구현
  .idea/.gitignore
  .idea/Let-s-git-it-started-2024.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  src/calc.java
Labels: Team5

#64 11/mul
  src/calc.js
Labels: Team2

#46 feat: 나눗셈
  src/calc.js
Labels: Team2
